version: '3.8'

# When running commands with this file, you must specify both this yml file and
# the correct env file. For example:
#   `docker-compose -f demo.yml --env-file=.demo_env up`
services:
  auth:
    build: ./sp
    image: ghcr.io/eclipse-pass/auth:0.1.1@sha256:a35038bb7a6403830fedb22bda545dc21b3ad8a093f26bdbecbf2c0a4f9cff86
    env_file: .demo_env
    container_name: auth
    networks:
      - front
      - back

  pass-core:
    image: ghcr.io/eclipse-pass/elide:0.2.0@sha256:de7aac5ad37b7b908f27ebad51f877e1f72078f45f1b26762e822c17b80af8af
    env_file: .demo_env
    container_name: pass-core
    networks:
      - back
    depends_on:
      - postgres
  
  pass-ui:
    image: ghcr.io/eclipse-pass/pass-ui:0.2.0@sha256:1eaac304cb392e97e939d00fb05877f0da3daf1d157b29fc4a75c1b849c8b291
    env_file: .demo_env
    container_name: pass-ui
    networks:
      - back # is 'back' in the main docker-compose, use this or 'front'?

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file: .demo_env
    networks:
      - back
    volumes: 
      - db:/var/lib/postgresql/data
      - ./postgres/demo/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
  
  proxy:
    build: ./demo-proxy/
    image: ghcr.io/eclipse-pass/proxy:0.2.0@sha256:5c9deba60e95e7aaf0db38b17523272bb01bdf26e92aeff77bdb5b9463a212af
    container_name: proxy
    networks:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"

  pass-ui-public:
    build:
      context: ./static-html
      args:
        STATIC_HTML_GIT_REPO: "${STATIC_HTML_GIT_REPO}"
        STATIC_HTML_GIT_BRANCH: "${STATIC_HTML_GIT_BRANCH}"
    image: ghcr.io/eclipse-pass/pass-ui-public:0.2.0@sha256:59288c8687050d3d8822b9b4b8903db599ce9ef44a392f8c151620fd23305f47
    container_name: pass-ui-public
    env_file: .demo_env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - front

  idp:
    build:
      context: ./idp
      args:
        TENANT: jhu
    image: ghcr.io/eclipse-pass/idp:0.2.0@sha256:48998d5160175c98742eea99ec29be63096d7d9407bdc6b99a97b4a89b5d657e
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    build:
      context: ./ldap
      args:
        TENANT: jhu
    image: oapass/ldap:0.1.0@sha256:059f4b287a8a1e8381afeca0e3e13b0255ccf2d93d50d8b318fc8d9826f5d5e5
    container_name: ldap
    networks:
     - back

  loader:
    image: ghcr.io/eclipse-pass/demo-loader:0.0.2@sha256:82efd5b465241c3e5f50cbcf4ca30e7e3d4d375a4abe05b7e0348542c85d5d0a
    env_file: .demo_env
    container_name: loader
    networks:
      - back
    depends_on:
      - pass-core

volumes:
  db:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem