#
# Copyright 2023 Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.8'

# The base docker-compose file for eclipse-pass.org deployments
# DO NOT CALL THIS directly, instead look at specific environments
#
#  - eclipse-pass.demo.yml
#  - eclipse-pass.nightly.yml
services:
  auth:
    image: "ghcr.io/eclipse-pass/pass-auth:${PASS_VERSION}"
    container_name: auth
    env_file:
      - .env
    networks:
      - front
      - back
    secrets:
     - source: sp_key
     - source: sp_cert
     - source: idp_cert

  pass-core:
    image: "ghcr.io/eclipse-pass/pass-core-main:${PASS_VERSION}"
    container_name: pass-core
    env_file:
      - .env
    networks:
      - back
    depends_on:
      - postgres
      - localstack
    healthcheck:
      test: "curl -u $PASS_CORE_BACKEND_USER:$PASS_CORE_BACKEND_PASSWORD -f http://pass-core:8080/data/user || exit 1"
      start_period: 30s

  pass-ui:
    image: "ghcr.io/eclipse-pass/pass-ui:${PASS_VERSION}"
    build:
      context: ./ember
      args:
        # required args (throw error during build):
        EMBER_GIT_PASS_UI_GIT_REPOREPO: "${PASS_UI_GIT_REPO:?undefined-PASS_UI_GIT_REPO}"
        PASS_UI_GIT_BRANCH: "${PASS_UI_GIT_BRANCH:?undefined-PASS_UI_GIT_BRANCH}"
        # sensible defaults have been defined:
        DOI_SERVICE_URL: "${DOI_SERVICE_URL:-}"
        MANUSCRIPT_SERVICE_LOOKUP_URL: "${MANUSCRIPT_SERVICE_LOOKUP_URL:-}"
        MANUSCRIPT_SERVICE_DOWNLOAD_URL: "${MANUSCRIPT_SERVICE_DOWNLOAD_URL:-}"
        METADATA_SCHEMA_URI: "${METADATA_SCHEMA_URI:-}"
        PASS_UI_PORT: "${PASS_UI_PORT:-}"
        PASS_API_NAMESPACE: "${PASS_API_NAMESPACE:-}"
        PASS_UI_ROOT_URL: "${PASS_UI_ROOT_URL:-}"
        POLICY_SERVICE_URL: "${POLICY_SERVICE_URL:-}"
        USER_SERVICE_URL: "${USER_SERVICE_URL:-}"
    container_name: pass-ui
    env_file:
      - .env
    networks:
      - back # is 'back' in the main docker-compose, use this or 'front'?

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    networks:
      - back
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/demo/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh

  proxy:
    build: ./demo-proxy/
    image: "ghcr.io/eclipse-pass/proxy:${PASS_VERSION}"
    container_name: proxy
    env_file:
      - .env
    networks:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"

  idp:
    build:
      context: ./idp
      args:
        TENANT: jhu
    image: "ghcr.io/eclipse-pass/idp:${PASS_VERSION}"
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    env_file:
      - .env
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer
     - source: idp_cert

  ldap:
    build:
      context: ./ldap
      args:
        TENANT: jhu
    image: "ghcr.io/eclipse-pass/demo-ldap:${PASS_VERSION}"
    container_name: ldap
    env_file:
      - .env
    networks:
     - back

  loader:
    image: curlimages/curl:7.87.0
    container_name: loader
    command: [curl, http://pass-core:8080/data/, -u, "$PASS_CORE_BACKEND_USER:$PASS_CORE_BACKEND_PASSWORD", -X, PATCH, -H, "content-type: application/vnd.api+json; ext=jsonpatch", -d, "@/data.json"]
    networks:
      - back
    depends_on:
      pass-core:
        condition: service_healthy
    volumes:
      - ./demo_data.json:/data.json

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/sqs_bootstrap.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - back

volumes:
  db:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  idp_cert:
    file: ./secrets/idp/idp-signing.crt
  sp_key:
    file: ./secrets/sp/sp-key.pem
  sp_cert:
    file: ./secrets/sp/sp-cert.pem
