version: '3.8'

# The base docker-compose file for eclipse-pass.org deployments
# DO NOT CALL THIS directly, instead look at specific environments
#
#  - eclipse-pass.demo.yml
#  - eclipse-pass.nightly.yml
services:
  auth:
    image: ghcr.io/eclipse-pass/pass-auth:0.3.0@sha256:c0f68f7823fb0a79cac4145f7769ede2b9aecafb133dc7d9fc39ccc6c19892c5
    container_name: auth
    env_file:
      - .env
    networks:
      - front
      - back
    secrets:
     - source: sp_key
     - source: sp_cert
     - source: idp_cert

  pass-core:
    image: ghcr.io/eclipse-pass/pass-core-main:0.3.0@sha256:3c4c5fdbaed397af0ac5bfa0f86111cf90aa4bd602312179e0691985e5c0b3d0
    container_name: pass-core
    env_file:
      - .env
    networks:
      - back
    depends_on:
      - postgres
    healthcheck:
      test: "curl -f http://pass-core:8080/data/user || exit 1"
      start_period: 30s

  pass-ui:
    image: ghcr.io/eclipse-pass/pass-ui:0.3.0@sha256:0834ad817e34aeca20991f03091a8fd178cfa57124d9cf27b1a8975359fa5aac
    build:
      context: ./ember
      args:
        # required args (throw error during build):
        EMBER_GIT_PASS_UI_GIT_REPOREPO: "${PASS_UI_GIT_REPO:?undefined-PASS_UI_GIT_REPO}"
        PASS_UI_GIT_BRANCH: "${PASS_UI_GIT_BRANCH:?undefined-PASS_UI_GIT_BRANCH}"
        # sensible defaults have been defined:
        DOI_SERVICE_URL: "${DOI_SERVICE_URL:-}"
        MANUSCRIPT_SERVICE_LOOKUP_URL: "${MANUSCRIPT_SERVICE_LOOKUP_URL:-}"
        MANUSCRIPT_SERVICE_DOWNLOAD_URL: "${MANUSCRIPT_SERVICE_DOWNLOAD_URL:-}"
        METADATA_SCHEMA_URI: "${METADATA_SCHEMA_URI:-}"
        PASS_UI_PORT: "${PASS_UI_PORT:-}"
        PASS_API_NAMESPACE: "${PASS_API_NAMESPACE:-}"
        PASS_UI_ROOT_URL: "${PASS_UI_ROOT_URL:-}"
        POLICY_SERVICE_URL: "${POLICY_SERVICE_URL:-}"
        USER_SERVICE_URL: "${USER_SERVICE_URL:-}"
    container_name: pass-ui
    env_file:
      - .env
    networks:
      - back # is 'back' in the main docker-compose, use this or 'front'?

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    networks:
      - back
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/demo/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh

  proxy:
    build: ./demo-proxy/
    image: ghcr.io/eclipse-pass/proxy:0.3.0@sha256:6020f7f017108fcc1911d94e0afafcbb5dd02f005876eaa5453395697627628c
    container_name: proxy
    env_file:
      - .env
    networks:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"

  pass-ui-public:
    build:
      context: ./static-html
      args:
        STATIC_HTML_GIT_REPO: "${STATIC_HTML_GIT_REPO}"
        STATIC_HTML_GIT_BRANCH: "${STATIC_HTML_GIT_BRANCH}"
    image: ghcr.io/eclipse-pass/pass-ui-public:0.3.0@sha256:cfe0b90db197aa460be2091e179978b6b95c73b8acb4278db86eed9876b4f1a8
    container_name: pass-ui-public
    env_file:
      - .env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - front

  idp:
    build:
      context: ./idp
      args:
        TENANT: jhu
    image: ghcr.io/eclipse-pass/idp:0.3.0@sha256:02235c80cda327375819d84074b165bf931b25e219aff100e8fad13c2a21800d
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    env_file:
      - .env
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer
     - source: idp_cert

  ldap:
    build:
      context: ./ldap
      args:
        TENANT: jhu
    image: ghcr.io/eclipse-pass/demo-ldap:0.3.0@sha256:331cd3ae9c3673c9439fa7465ee807172702bc3dac6583c173766e3c036e8c3e
    container_name: ldap
    env_file:
      - .env
    networks:
     - back

  loader:
    image: curlimages/curl:7.87.0
    container_name: loader
    command: [curl, http://pass-core:8080/data/, -X, PATCH, -H, "content-type: application/vnd.api+json; ext=jsonpatch", -d, "@/data.json"]
    networks:
      - back
    depends_on:
      pass-core:
        condition: service_healthy
    volumes:
      - ./demo_data.json:/data.json

volumes:
  db:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  idp_cert:
    file: ./secrets/idp/idp-signing.crt
  sp_key:
    file: ./secrets/sp/sp-key.pem
  sp_cert:
    file: ./secrets/sp/sp-cert.pem