#
# Copyright 2023 Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# The docker-compose file to start PASS deposit services connecting to running invenioRDM docker compose.

services:
  deposit-services:
    env_file:
      - .env
      - .eclipse-pass.local_env
      - invenio-rdm/pass-docker-invenio-rdm/.eclipse-pass.invenio.local_env
    networks:
      - back
      - pass-docker-invenio-rdm_default
    volumes:
      - ./deposit/deposit-repositories.json:/deposit/deposit-repositories.json
      - ./deposit/localtest.jks:/certificates/localtest.jks

networks:
  pass-docker-invenio-rdm_default:
    name: pass-docker-invenio-rdm_default
    external: true
