# Env customizations for a local development instance
version: '3.8'

services:
  auth:
    env_file:
      - .eclipse-pass.local_env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - source: sp_key
      - source: sp_cert
      - source: idp_cert

  proxy:
    env_file:
      - .eclipse-pass.local_env

  pass-core:
    depends_on:
      - postgres
      - localstack
    env_file:
      - .eclipse-pass.local_env
    healthcheck:
      test: 'curl -u "$$PASS_CORE_BACKEND_USER:$$PASS_CORE_BACKEND_PASSWORD" -f http://pass-core:8080/data/user || exit 1'
      start_period: 30s

  pass-ui:
    env_file:
      - .eclipse-pass.local_env

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
      - .eclipse-pass.local_env
    networks:
      - back
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/demo/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh

  idp:
    build:
      context: ./idp
      args:
        TENANT: jhu
    image: "ghcr.io/eclipse-pass/idp:${PASS_VERSION}"
    container_name: idp
    depends_on:
      - ldap
    environment:
      - JETTY_MAX_HEAP=64m
      - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
      - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
      - "4443"
    env_file:
      - .env
      - .eclipse-pass.local_env
    networks:
      - back
    secrets:
      - source: idp_backchannel
      - source: idp_browser
      - source: idp_encryption
      - source: idp_signing
      - source: idp_sealer
      - source: idp_cert

  ldap:
    build:
      context: ./ldap
      args:
        TENANT: jhu
    image: "ghcr.io/eclipse-pass/demo-ldap:${PASS_VERSION}"
    container_name: ldap
    env_file:
      - .env
      - .eclipse-pass.local_env
    networks:
      - back

  loader:
    image: curlimages/curl:7.87.0
    container_name: loader
    env_file:
      - .env
      - .eclipse-pass.local_env
    entrypoint: /bin/sh -c
    command: [ 'curl http://pass-core:8080/data/ -u "$$PASS_CORE_BACKEND_USER:$$PASS_CORE_BACKEND_PASSWORD" -X PATCH -H "content-type: application/vnd.api+json;ext=jsonpatch" -H "accept:application/vnd.api+json; ext=jsonpatch" -d "@/data.json"' ]
    networks:
      - back
    depends_on:
      pass-core:
        condition: service_healthy
    volumes:
      - ./demo_data.json:/data.json

  localstack:
    container_name: "localstack"
    image: localstack/localstack:3.2.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack/aws_bootstrap.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - back

secrets:
  idp_cert:
    file: ./secrets/idp/idp-signing.crt
  sp_key:
    file: ./secrets/sp/sp-key.pem
  sp_cert:
    file: ./secrets/sp/sp-cert.pem
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks