version: '3.8'

# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file: .eclipse-pass.nightly_env

  pass-core:
    env_file: .eclipse-pass.nightly_env
    image: ghcr.io/eclipse-pass/pass-core-main:0.2.0-SNAPSHOT@sha256:421a8e8de6d7038a4d093b6403db12255e66ee9e3cf78780847a169465ff0b02

  pass-ui:
    env_file: .eclipse-pass.nightly_env

  postgres:
    env_file: .eclipse-pass.nightly_env

  pass-ui-public:
    env_file: .eclipse-pass.nightly_env

  loader:
    env_file: .eclipse-pass.nightly_env
