name: PASS acceptance tests
description: >
  Run acceptance tests.
  
  Assumes you are in the pass-docker project. Will start up the Compose environment
  and tear it down when complete

inputs:
  timeouts:
    description: 'Testing timeouts (ms)'
    default: '60000'
  pullimages:
    description: 'Image pull policy (always|missing|never) [default: always]'
    default: 'always'

runs:
  using: composite
  steps:
    - name: Append hosts file to enable "pass.local" on localhost
      shell: bash
      run: echo "127.0.0.1    pass.local" | sudo tee -a /etc/hosts

    - name: Run pass-docker
      shell: bash
      run: docker compose -f docker-compose.yml -f eclipse-pass.local.yml up -d --no-build --quiet-pull --pull ${{ inputs.pullimages }}

    - name: Checkout pass-acceptance-testing
      uses: actions/checkout@v3
      with:
        repository: eclipse-pass/pass-acceptance-testing
        path: pass-acceptance-testing

    # Can run `yarn test`, but calling testcafe directly allows us to more easily set test timeouts
    - name: Run acceptance tests
      run: |
        cd pass-acceptance-testing
        yarn install --frozen-lockfile
        npx testcafe 'chrome --ignore-certificate-errors --allow-insecure-localhost' \
          --hostname localhost \
          tests/*Tests.js \
          --selector-timeout ${{ inputs.timeouts}} \
          --assertion-timeout ${{ inputs.timeouts}} \
          --ajax-request-timeout ${{ inputs.timeouts}}

    - name: Stop pass-docker
      shell: bash
      run: cd .. && docker compose down -v