name: Debug test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Append hosts file
        run: |
          echo "127.0.0.1 pass.local" | sudo tee -a /etc/hosts
          cat /etc/hosts