name: pass-acceptance-testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Append hosts file
      run: echo "127.0.1 pass.local" | sudo tee -a /etc/hosts
    - name: Checkout pass-docker
      uses: actions/checkout@v3

    - name: Checkout pass-acceptance-testing
      uses: actions/checkout@v3
      with:
        repository: eclipse-pass/pass-acceptance-testing
        path: pass-acceptance-testing
    - name: Setup Yarn 
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: yarn install
    
    - name: Run pass-docker
      run: |
        docker-compose pull
        docker-compose up -d

    - name: Run acceptance tests
      uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome ./pass-acceptance-testing/tests/*Tests.js"
