name: pass-acceptance-testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
  schedule:
    - cron: "0 2 * * *"

env:
  TIMEOUT_LENGTH: 120000

jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pass-docker
      uses: actions/checkout@v3

    - name: Run acceptance tests
      uses: ./.github/actions/acceptance-test
      with:
        timeouts: $TIMEOUT_LENGTH
