  # Update Docker images in pass-docker that are build in this repository:
  #   * idp
  #   * ldap
name: update-docker-images

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update-images:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build set of Docker images
        run: docker compose -f docker-compose.yml -f eclipse-pass.local.yml build --no-cache idp ldap

      - name: Publish Docker images
        run: docker compose -f docker-compose.yml -f eclipse-pass.local.yml push idp ldap
